"""
Cell-aware Routing Loader (EDGE.md → runtime)

Reads `modules/routing_table.json` (generated by tools/edge_md_export.py) and
exposes get_routing(strategy, instrument, cell3d) -> "BLOCK"|"KELLY_HALF"|
"KELLY_FULL"|"NONE".

The table is reloaded at most every CACHE_TTL seconds. Reads are non-blocking;
on any I/O or parse error, returns "NONE" (fail-open) and logs a warning.

Design notes:
  - Pair (instrument) is currently unused in routing keys (cell3d is per-pair
    via classifier). The argument is kept for future extension (e.g. pair-
    qualified BLOCK).
  - All decisions are O(1) via set lookup.
"""
from __future__ import annotations

import json
import os
import time
import threading
from pathlib import Path

_DEFAULT_PATH = Path(os.path.dirname(os.path.abspath(__file__))) / "routing_table.json"
CACHE_TTL = 60  # seconds

_lock = threading.Lock()
_cache = {
    "ts": 0.0,
    "block": frozenset(),
    "kelly_half": {},   # {(strategy, cell): multiplier}
    "kelly_full": {},   # {(strategy, cell): multiplier}
    "edges_count": 0,
    "loaded_path": None,
}


def _do_load(path: Path) -> dict:
    with path.open() as f:
        data = json.load(f)
    block = frozenset((s, c) for s, c, *_ in data.get("block", []))
    kh = {(row[0], row[1]): (row[2] if len(row) > 2 else 0.5)
          for row in data.get("kelly_half", [])}
    kf = {(row[0], row[1]): (row[2] if len(row) > 2 else 1.0)
          for row in data.get("kelly_full", [])}
    return {
        "block": block,
        "kelly_half": kh,
        "kelly_full": kf,
        "edges_count": data.get("edges_count", 0),
    }


def load_routing(path: Path = _DEFAULT_PATH, ttl: int = CACHE_TTL,
                 force: bool = False) -> dict:
    """Return cached routing table, refreshing if stale.

    On error, return the previous cache (or empty defaults if never loaded).
    """
    now = time.time()
    with _lock:
        if not force and (now - _cache["ts"]) < ttl and _cache["loaded_path"] is not None:
            return _cache
        try:
            if path.exists():
                fresh = _do_load(path)
                _cache.update(fresh)
                _cache["ts"] = now
                _cache["loaded_path"] = str(path)
        except Exception as e:
            # Fail open: keep prior cache. Surface via stderr but don't raise.
            import sys
            print(f"[cell_routing] load error from {path}: {e}", file=sys.stderr)
        return _cache


def get_routing(strategy: str, instrument: str, cell3d: str,
                path: Path = _DEFAULT_PATH) -> str:
    """Return one of "BLOCK", "KELLY_HALF", "KELLY_FULL", "NONE".

    Args:
        strategy: entry_type identifier
        instrument: e.g. "USD_JPY" (currently unused, reserved for future)
        cell3d: "{regime}__{vol}__{session}" or None/""

    Returns:
        Routing decision string. "NONE" when no edge matches or input invalid.
    """
    if not strategy or not cell3d:
        return "NONE"
    table = load_routing(path)
    key = (strategy, cell3d)
    if key in table["block"]:
        return "BLOCK"
    if key in table["kelly_full"]:
        return "KELLY_FULL"
    if key in table["kelly_half"]:
        return "KELLY_HALF"
    return "NONE"


def get_lot_multiplier(strategy: str, instrument: str, cell3d: str,
                       path: Path = _DEFAULT_PATH) -> float:
    """Return Kelly fraction multiplier (0.5 / 1.0) or 1.0 if NONE/BLOCK.

    Caller decides whether BLOCK short-circuits before reaching here.
    """
    if not strategy or not cell3d:
        return 1.0
    table = load_routing(path)
    key = (strategy, cell3d)
    if key in table["kelly_full"]:
        return float(table["kelly_full"][key])
    if key in table["kelly_half"]:
        return float(table["kelly_half"][key])
    return 1.0


def routing_summary(path: Path = _DEFAULT_PATH) -> dict:
    """Return counts for monitoring."""
    t = load_routing(path)
    return {
        "edges_count": t.get("edges_count", 0),
        "block": len(t["block"]),
        "kelly_half": len(t["kelly_half"]),
        "kelly_full": len(t["kelly_full"]),
        "loaded_at": t["ts"],
        "loaded_path": t["loaded_path"],
    }
