#!/usr/bin/env bash
# One-time setup: create the self-hosted environment + 4 agents via the `ant` CLI.
# Order matters: sub-agents first -> capture IDs -> coordinator references them.
# Prereqs: `ant` installed + authed (ant auth login), ANTHROPIC_API_KEY unset if using a profile.
set -euo pipefail
cd "$(dirname "$0")"

# 環境は冪等に: 既存の fxai-selfhosted があれば再利用、無ければ作成 (409回避)
ENV_ID=$(ant beta:environments list --transform '{id,name}' --format jsonl 2>/dev/null \
  | grep '"name":"fxai-selfhosted"' | sed -E 's/.*"id":"([^"]+)".*/\1/' | head -1)
[ -z "$ENV_ID" ] && ENV_ID=$(ant beta:environments create < env.self-hosted.yaml --transform id -r)
RID=$(ant beta:agents create < research.agent.yaml  --transform id -r)
DID=$(ant beta:agents create < dev.agent.yaml       --transform id -r)
VID=$(ant beta:agents create < reviewer.agent.yaml  --transform id -r)
CID=$(sed -e "s/AGENT_ID_RESEARCH/$RID/" -e "s/AGENT_ID_DEV/$DID/" -e "s/AGENT_ID_REVIEW/$VID/" \
        coordinator.agent.yaml | ant beta:agents create --transform id -r)

cat > ids.env <<EOF
# generated by setup.sh — source this before worker.py / driver.py
export ANTHROPIC_ENVIRONMENT_ID=$ENV_ID
export FXAI_ENV_ID=$ENV_ID
export FXAI_RESEARCH_ID=$RID
export FXAI_DEV_ID=$DID
export FXAI_REVIEWER_ID=$VID
export FXAI_COORDINATOR_ID=$CID
# still needed manually:
#   export ANTHROPIC_ENVIRONMENT_KEY=sk-ant-oat01-...   (Console -> environment -> Generate key)
#   export GITHUB_VAULT_ID=vlt_...                      (see README: GitHub MCP vault)
EOF

echo "Created. IDs written to agents/cma/ids.env"
echo "  ENV=$ENV_ID  RESEARCH=$RID  DEV=$DID  REVIEWER=$VID  COORDINATOR=$CID"
echo "Next: generate ANTHROPIC_ENVIRONMENT_KEY in Console, then run the reviewer smoke test (README step B)."
