#!/usr/bin/env python3
"""BT trade_log → TradingView Pine overlay generator.

Runs production daytrade BT, filters trade_log by entry_type, emits a Pine v5
indicator that plots each trade as a label + SL/TP lines at the BT entry bar.
Use it to visually confirm whether a Python BT edge actually fires in the same
location/direction on a TV chart.

Usage:
    BT_MODE=1 python3 tools/tv_overlay_gen.py <entry_type> <symbol> [lookback_days] [interval]

Example:
    BT_MODE=1 python3 tools/tv_overlay_gen.py trendline_sweep EURUSD=X 365 15m
"""
import os
import sys
import json
import time
from datetime import datetime, timezone

os.environ.setdefault("BT_MODE", "1")
os.environ.setdefault("NO_AUTOSTART", "1")

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _parse_entry_time_ms(s: str) -> int:
    """Parse trade['entry_time'] (str(pandas.Timestamp)) → Unix ms (UTC)."""
    import pandas as pd
    ts = pd.Timestamp(s)
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    else:
        ts = ts.tz_convert("UTC")
    return int(ts.value // 10**6)


def _tv_symbol_for(py_symbol: str) -> str:
    """Map yfinance ticker → TradingView ticker (FX_IDC fallback)."""
    s = py_symbol.replace("=X", "").upper()
    return f"FX_IDC:{s}"


def _pair_for_friction(py_symbol: str) -> str:
    return py_symbol.replace("=X", "").upper()


def generate_pine(entry_type: str, symbol: str, lookback_days: int, interval: str, trade_log: list) -> str:
    """Build a Pine v5 indicator string with hardcoded trade arrays."""
    # Filter trades
    filtered = [t for t in trade_log if t.get("entry_type") == entry_type]
    print(f"\nFiltered {len(filtered)} {entry_type} trades from total {len(trade_log)}")
    if not filtered:
        raise SystemExit(f"No trades with entry_type={entry_type} found in BT result")

    # Build arrays
    ts_ms, sigs, eps, sls, tps, outs, holds = [], [], [], [], [], [], []
    for t in filtered:
        ts_ms.append(_parse_entry_time_ms(t["entry_time"]))
        sigs.append(1 if t["sig"] == "BUY" else -1)
        eps.append(float(t["ep"]))
        sls.append(float(t["sl"]))
        tps.append(float(t["tp"]))
        outs.append(1 if t["outcome"] == "WIN" else 0)
        holds.append(int(t.get("bars_held", 0)))

    title = f"BT Overlay: {entry_type} {symbol} {lookback_days}d {interval}"
    n = len(filtered)
    wins = sum(outs)
    wr = round(wins / n * 100, 1) if n else 0

    pine = f"""//@version=5
indicator("{title}", overlay=true, max_labels_count=500, max_lines_count=500)

// ─────────────────────────────────────────────────────────
// Auto-generated by tools/tv_overlay_gen.py
// Strategy   : {entry_type}
// Symbol     : {symbol}  (TV: {_tv_symbol_for(symbol)})
// Lookback   : {lookback_days}d / {interval}
// Trade count: {n}  (WIN={wins}, WR={wr}%)
// Generated  : {datetime.now(timezone.utc).isoformat()}
// ─────────────────────────────────────────────────────────

show_lines = input.bool(true,  "Show SL/TP lines")
show_labels = input.bool(true, "Show entry labels")
line_len_bars = input.int(30, "SL/TP line length (bars)", minval=1, maxval=200)

// Trade arrays (entry timestamp Unix ms UTC, direction, prices, outcome)
var int[]   T_TS  = array.from({", ".join(str(x) for x in ts_ms)})
var int[]   T_SIG = array.from({", ".join(str(x) for x in sigs)})
var float[] T_EP  = array.from({", ".join(f"{x:.6f}" for x in eps)})
var float[] T_SL  = array.from({", ".join(f"{x:.6f}" for x in sls)})
var float[] T_TP  = array.from({", ".join(f"{x:.6f}" for x in tps)})
var int[]   T_OUT = array.from({", ".join(str(x) for x in outs)})
var int[]   T_HOLD = array.from({", ".join(str(x) for x in holds)})

// Walk each trade and plot once when bar's time matches the entry timestamp
plot_one(int idx) =>
    int   ts_target = array.get(T_TS, idx)
    int   sig       = array.get(T_SIG, idx)
    float ep        = array.get(T_EP, idx)
    float slv       = array.get(T_SL, idx)
    float tpv       = array.get(T_TP, idx)
    int   ow        = array.get(T_OUT, idx)
    int   hold      = array.get(T_HOLD, idx)

    bool hit = (time == ts_target) or (time <= ts_target and time_close > ts_target)
    if hit
        color cwin  = ow == 1 ? color.new(color.lime, 0)   : color.new(color.red, 0)
        color cep   = color.new(color.yellow, 20)
        string txt  = (sig == 1 ? "▲BUY " : "▼SELL ") + (ow == 1 ? "WIN" : "LOSS") + " h=" + str.tostring(hold)
        style_lab = sig == 1 ? label.style_label_up : label.style_label_down
        if show_labels
            label.new(bar_index, sig == 1 ? low : high, text=txt, color=cwin, textcolor=color.white, style=style_lab, size=size.small)
        if show_lines
            line.new(bar_index, ep,  bar_index + line_len_bars, ep,  color=cep, width=1, style=line.style_dashed)
            line.new(bar_index, slv, bar_index + line_len_bars, slv, color=color.new(color.red, 30),  width=1)
            line.new(bar_index, tpv, bar_index + line_len_bars, tpv, color=color.new(color.green, 30), width=1)

// Run once per bar — iterate all trades, only the bar matching ts will paint
var int last_seen_bar = -1
if bar_index != last_seen_bar
    last_seen_bar := bar_index
    int n = array.size(T_TS)
    for i = 0 to n - 1
        plot_one(i)

// Stats panel
var table stats = table.new(position.top_right, 2, 5, border_width=1)
if barstate.islast
    table.cell(stats, 0, 0, "Strategy", bgcolor=color.gray, text_color=color.white)
    table.cell(stats, 1, 0, "{entry_type}", text_color=color.white)
    table.cell(stats, 0, 1, "Pair", bgcolor=color.gray, text_color=color.white)
    table.cell(stats, 1, 1, "{_pair_for_friction(symbol)} {interval}", text_color=color.white)
    table.cell(stats, 0, 2, "BT N", bgcolor=color.gray, text_color=color.white)
    table.cell(stats, 1, 2, str.tostring({n}), text_color=color.white)
    table.cell(stats, 0, 3, "WR", bgcolor=color.gray, text_color=color.white)
    table.cell(stats, 1, 3, "{wr}%", text_color=color.white)
    table.cell(stats, 0, 4, "Lookback", bgcolor=color.gray, text_color=color.white)
    table.cell(stats, 1, 4, "{lookback_days}d", text_color=color.white)
"""
    return pine


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    entry_type = sys.argv[1]
    symbol = sys.argv[2]
    lookback = int(sys.argv[3]) if len(sys.argv) > 3 else 365
    interval = sys.argv[4] if len(sys.argv) > 4 else "15m"

    print(f"Importing app.py ...")
    t0 = time.time()
    import app
    print(f"  imported in {time.time()-t0:.1f}s")

    print(f"\nRunning BT: {symbol} × {lookback}d {interval}")
    app._dt_bt_cache.clear()
    t1 = time.time()
    result = app.run_daytrade_backtest(symbol, lookback_days=lookback, interval=interval)
    elapsed = time.time() - t1

    if result.get("error"):
        print(f"BT error: {result['error']}")
        sys.exit(2)

    print(f"BT done in {elapsed:.0f}s — total trades={result.get('trades')}")
    eb = result.get("entry_breakdown", {}).get(entry_type)
    if eb:
        print(f"  {entry_type}: N={eb.get('total')} WR={eb.get('win_rate')}% EV={eb.get('ev')} PnL={eb.get('pnl')}")
    else:
        print(f"  WARNING: no entry_breakdown for {entry_type}")

    trade_log = result.get("trade_log", [])
    pine = generate_pine(entry_type, symbol, lookback, interval, trade_log)

    # Save under bt-results/ with a stable name; also keep one date-stamped copy
    out_dir = "/Users/jg-n-012/test/fx-ai-trader/bt-results/tv-overlays"
    os.makedirs(out_dir, exist_ok=True)
    safe_sym = symbol.replace("=X", "").upper()
    stamp = datetime.now().strftime("%Y-%m-%d")
    pine_path = f"{out_dir}/{entry_type}-{safe_sym}-{interval}-{lookback}d-{stamp}.pine"
    json_path = f"{out_dir}/{entry_type}-{safe_sym}-{interval}-{lookback}d-{stamp}.trades.json"

    with open(pine_path, "w") as f:
        f.write(pine)
    print(f"\nPine written: {pine_path}  ({len(pine)} bytes)")

    # Save the filtered trade_log too for re-use
    filtered = [t for t in trade_log if t.get("entry_type") == entry_type]
    with open(json_path, "w") as f:
        json.dump({"strategy": entry_type, "symbol": symbol, "lookback_days": lookback,
                   "interval": interval, "generated_at": datetime.now(timezone.utc).isoformat(),
                   "trades": filtered}, f, indent=2, default=str)
    print(f"Trade log written: {json_path}  ({len(filtered)} trades)")


if __name__ == "__main__":
    main()
